import * as cdk from 'aws-cdk-lib';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as cognito from 'aws-cdk-lib/aws-cognito';
import * as kms from 'aws-cdk-lib/aws-kms';
import * as s3n from 'aws-cdk-lib/aws-s3-notifications';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import * as ssm from 'aws-cdk-lib/aws-ssm';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as subscriptions from 'aws-cdk-lib/aws-sns-subscriptions';
import * as path from 'path';
import { Construct } from 'constructs';

export interface EcsLogGatewayV2Props {
  readonly gatewayName?: string;
  readonly cognitoUserPoolName?: string;
  readonly resourceServerName?: string;
  readonly logRetentionDays?: number;
  readonly enableKmsEncryption?: boolean;
  readonly sopBucketName?: string;

  /**
   * Exact ECS cluster names this deployment may inspect or mutate.
   * This property is mandatory and must contain at least one valid ECS name.
   */
  readonly allowedClusterNames?: string[];

  /**
   * Explicit list of AWS regions permitted for cross-region SSM execution.
   * Used for IAM aws:RequestedRegion conditions and Lambda ALLOWED_REGIONS env var.
   * @default [Stack region]
   */
  readonly allowedRegions?: string[];

  /**
   * IAM role ARNs for ECS container instances that need KMS encrypt and S3 PutObject access.
   * At least one explicit role is required; no account-wide compatibility fallback exists.
   */
  readonly ecsInstanceRoleArns?: string[];

  /**
   * Presigned URL expiration in seconds for all S3 presigned URLs generated by the Lambda.
   * @default 900
   */
  readonly presignedUrlExpirationSeconds?: number;

  /**
   * IAM role ARN for the SSM Default Host Management Configuration role.
   * This role needs S3 PutObject and KMS Encrypt to upload collected logs.
   * @default undefined
   */
  readonly ssmDefaultHostRoleArn?: string;

  /** Require native SSM human approval before collection and tcpdump execution. @default true */
  readonly requireCollectionApproval?: boolean;

  /** IAM user/role ARNs allowed to approve. Required when approval is enabled. */
  readonly approvalApproverArns?: string[];

  /** Email subscriptions created on the approval SNS topic. @default [] */
  readonly approvalNotificationEmails?: string[];

  /** Approval wait timeout in seconds. @default 900 */
  readonly approvalTtlSeconds?: number;

  /** Restricted MCP tools to expose, for example tcpdump_capture and tcpdump_analyze. @default [] */
  readonly enableRestrictedTools?: string[];

  /** Presigned URL expiration for packet captures. @default 60 */
  readonly pcapPresignedUrlExpirationSeconds?: number;

  /** Advisory maximum packet capture size in bytes. @default 209715200 */
  readonly maxPcapBytes?: number;
}

export class EcsLogGatewayConstructV2 extends Construct {
  public readonly logsBucket: s3.Bucket;
  public readonly kmsKey: kms.Key;
  public readonly ssmAutomationFunction: lambda.Function;
  public readonly unzipFunction: lambda.Function;
  public readonly findingsIndexerFunction: lambda.Function;
  public readonly userPool: cognito.UserPool;
  public readonly userPoolClient: cognito.UserPoolClient;
  public readonly ssmAutomationRole: iam.Role;
  public readonly gatewayExecutionRole: iam.Role;
  public readonly sopBucket: s3.Bucket;
  public readonly collectionApprovalTopic: sns.Topic;

  constructor(scope: Construct, id: string, props: EcsLogGatewayV2Props = {}) {
    super(scope, id);

    const gatewayName = props.gatewayName ?? 'EcsInstanceLogMcpGW';
    const cognitoUserPoolName = props.cognitoUserPoolName ?? 'ecs-log-gateway-pool';
    const resourceServerName = props.resourceServerName ?? 'ecs-log-gateway-id';
    const logRetentionDays = props.logRetentionDays ?? 1;
    const enableKmsEncryption = props.enableKmsEncryption ?? true;
    const requireCollectionApproval = props.requireCollectionApproval ?? true;
    const approvalTtlSeconds = props.approvalTtlSeconds ?? 900;
    const approverArns = props.approvalApproverArns ?? [];
    const enabledRestrictedTools = props.enableRestrictedTools ?? [];
    const allowedClusterNames = Array.from(new Set(
      (props.allowedClusterNames ?? []).map(value => value.trim()).filter(Boolean),
    ));
    const ecsInstanceRoleArns = Array.from(new Set(
      (props.ecsInstanceRoleArns ?? []).map(value => value.trim()).filter(Boolean),
    ));

    if (!enableKmsEncryption) {
      throw new Error('EcsLogGatewayV2: KMS encryption is mandatory and cannot be disabled.');
    }
    if (allowedClusterNames.length === 0 || allowedClusterNames.some(
      name => !/^[A-Za-z0-9_-]{1,255}$/.test(name),
    )) {
      throw new Error(
        'EcsLogGatewayV2: `allowedClusterNames` must contain at least one valid ECS cluster name.',
      );
    }
    const stack = cdk.Stack.of(this);
    const stackAccount = stack.account;
    if (ecsInstanceRoleArns.length === 0 || ecsInstanceRoleArns.some(arn => {
      const match = /^arn:(aws|aws-us-gov|aws-cn):iam::(\d{12}):role\/[A-Za-z0-9+=,.@_\/-]{1,512}$/.exec(arn);
      return !match || (!cdk.Token.isUnresolved(stackAccount) && match[2] !== stackAccount);
    })) {
      throw new Error(
        'EcsLogGatewayV2: `ecsInstanceRoleArns` must contain at least one explicit IAM role ARN from the stack account.',
      );
    }

    if (requireCollectionApproval && (
      approverArns.length === 0 || approverArns.some(arn => {
        const match = /^arn:(aws|aws-us-gov|aws-cn):iam::(\d{12}):(user|role)\/[A-Za-z0-9+=,.@_\/-]{1,512}$/.exec(arn);
        return !match || (!cdk.Token.isUnresolved(stackAccount) && match[2] !== stackAccount);
      })
    )) {
      throw new Error(
        'EcsLogGatewayV2: approval is enabled but `approvalApproverArns` does not contain ' +
        'a valid IAM user or role ARN from the stack account. Set APPROVAL_APPROVER_ARNS, ' +
        'or explicitly set REQUIRE_COLLECTION_APPROVAL=false for a supervised/test deployment.',
      );
    }

    const configuredRegions = Array.from(new Set(
      (props.allowedRegions ?? []).map(value => value.trim()).filter(Boolean),
    ));
    const allowedRegions = configuredRegions.length > 0 ? configuredRegions : [stack.region];
    if (allowedRegions.some(region => (
      !cdk.Token.isUnresolved(region) && !/^[a-z]{2}(?:-[a-z0-9]+)+-\d+$/.test(region)
    ))) {
      throw new Error('EcsLogGatewayV2: `allowedRegions` contains an invalid AWS region.');
    }
    if (
      requireCollectionApproval
      && !cdk.Token.isUnresolved(stack.region)
      && !allowedRegions.includes(stack.region)
    ) {
      throw new Error(
        'EcsLogGatewayV2: `allowedRegions` must include the stack region when approval is enabled.',
      );
    }

    const partition = stack.partition;
    const collectApprovalDocName = `${stack.stackName}-collect-with-approval`;
    const batchApprovalDocName = `${stack.stackName}-batch-collect-with-approval`;
    const tcpdumpApprovalDocName = `${stack.stackName}-tcpdump-with-approval`;

    // ========================================================================
    // KMS KEY (Mandatory)
    // ========================================================================
    this.kmsKey = new kms.Key(this, 'LogsEncryptionKey', {
      alias: `${cdk.Stack.of(this).stackName}-logs-key`,
      description: 'KMS key for ECS log encryption',
      enableKeyRotation: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    this.kmsKey.addToResourcePolicy(new iam.PolicyStatement({
      sid: 'AllowECSInstanceRolesEncrypt',
      effect: iam.Effect.ALLOW,
      principals: ecsInstanceRoleArns.map(arn => new iam.ArnPrincipal(arn)),
      actions: ['kms:GenerateDataKey', 'kms:Encrypt'],
      resources: ['*'],
    }));

    if (props.ssmDefaultHostRoleArn) {
      this.kmsKey.addToResourcePolicy(new iam.PolicyStatement({
        sid: 'AllowSSMDefaultHostRoleEncrypt',
        effect: iam.Effect.ALLOW,
        principals: [new iam.ArnPrincipal(props.ssmDefaultHostRoleArn)],
        actions: ['kms:GenerateDataKey', 'kms:Encrypt'],
        resources: ['*'],
      }));
    }

    // ========================================================================
    // IAM ROLES
    // ========================================================================
    this.ssmAutomationRole = new iam.Role(this, 'SSMAutomationRole', {
      roleName: `${cdk.Stack.of(this).stackName}-ssm-automation-role`,
      assumedBy: new iam.ServicePrincipal('ssm.amazonaws.com'),
    });

    const supportAutomationResources = allowedRegions.flatMap(region => [
      `arn:${partition}:ssm:${region}::automation-definition/AWSSupport-CollectECSInstanceLogs:*`,
      `arn:${partition}:ssm:${region}::document/AWSSupport-CollectECSInstanceLogs`,
      `arn:${partition}:ssm:${region}:${stack.account}:automation-execution/*`,
    ]);
    const runShellDocumentResources = allowedRegions.map(
      region => `arn:${partition}:ssm:${region}::document/AWS-RunShellScript`,
    );
    const allowedInstanceResources = allowedRegions.map(
      region => `arn:${partition}:ec2:${region}:${stack.account}:instance/*`,
    );
    const requestedRegionCondition = {
      StringEquals: { 'aws:RequestedRegion': allowedRegions },
    };

    this.ssmAutomationRole.addToPolicy(new iam.PolicyStatement({
      sid: 'StartSupportCollectionAutomation',
      effect: iam.Effect.ALLOW,
      actions: ['ssm:StartAutomationExecution'],
      resources: supportAutomationResources,
    }));

    this.ssmAutomationRole.addToPolicy(new iam.PolicyStatement({
      sid: 'SendRunShellScriptDocument',
      effect: iam.Effect.ALLOW,
      actions: ['ssm:SendCommand'],
      resources: runShellDocumentResources,
    }));

    this.ssmAutomationRole.addToPolicy(new iam.PolicyStatement({
      sid: 'SendCommandToAllowedRegionInstances',
      effect: iam.Effect.ALLOW,
      actions: ['ssm:SendCommand'],
      resources: allowedInstanceResources,
    }));

    this.ssmAutomationRole.addToPolicy(new iam.PolicyStatement({
      sid: 'ReadAutomationExecutions',
      effect: iam.Effect.ALLOW,
      actions: ['ssm:GetAutomationExecution', 'ssm:StopAutomationExecution'],
      resources: allowedRegions.map(
        region => `arn:${partition}:ssm:${region}:${stack.account}:automation-execution/*`,
      ),
    }));

    this.ssmAutomationRole.addToPolicy(new iam.PolicyStatement({
      sid: 'RegionalSsmReadAndCommandControl',
      effect: iam.Effect.ALLOW,
      actions: [
        'ssm:DescribeAutomationExecutions', 'ssm:GetCommandInvocation',
        'ssm:ListCommandInvocations', 'ssm:ListCommands', 'ssm:CancelCommand',
        'ssm:DescribeInstanceInformation',
      ],
      resources: ['*'],
      conditions: requestedRegionCondition,
    }));

    this.ssmAutomationRole.addToPolicy(new iam.PolicyStatement({
      sid: 'ReadRequiredSsmDocuments',
      effect: iam.Effect.ALLOW,
      actions: ['ssm:GetDocument', 'ssm:DescribeDocument'],
      resources: [
        ...allowedRegions.map(
          region => `arn:${partition}:ssm:${region}::document/AWSSupport-CollectECSInstanceLogs`,
        ),
        ...runShellDocumentResources,
      ],
    }));

    this.ssmAutomationRole.addToPolicy(new iam.PolicyStatement({
      sid: 'RegionalEcsInstanceRead',
      effect: iam.Effect.ALLOW,
      actions: [
        'ec2:DescribeInstances', 'ec2:DescribeInstanceStatus',
        'ecs:DescribeClusters',
        'ecs:DescribeContainerInstances', 'ecs:ListContainerInstances',
      ],
      resources: ['*'],
      conditions: requestedRegionCondition,
    }));

    // ========================================================================
    // S3 BUCKET
    // ========================================================================
    const bucketProps: s3.BucketProps = {
      bucketName: `${cdk.Stack.of(this).stackName.toLowerCase()}-logs-${cdk.Stack.of(this).account}`,
      versioned: true,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      lifecycleRules: [
        {
          id: 'DeleteOldLogsAndVersions',
          enabled: true,
          expiration: cdk.Duration.days(logRetentionDays),
          noncurrentVersionExpiration: cdk.Duration.days(Math.max(logRetentionDays + 1, 2)),
          abortIncompleteMultipartUploadAfter: cdk.Duration.days(1),
        },
        {
          id: 'DeleteExpiredObjectMarkers',
          enabled: true,
          expiredObjectDeleteMarker: true,
        },
        {
          id: 'DeleteOldIdempotencyMappings',
          enabled: true,
          prefix: 'idempotency/',
          expiration: cdk.Duration.days(7),
          noncurrentVersionExpiration: cdk.Duration.days(8),
        },
        {
          id: 'DeleteExecutionAndBatchMetadata',
          enabled: true,
          prefix: '_metadata/',
          expiration: cdk.Duration.days(7),
          noncurrentVersionExpiration: cdk.Duration.days(8),
        },
        { id: 'ExpireOldBaselines', enabled: true, prefix: 'baselines/', expiration: cdk.Duration.days(90) },
        { id: 'ExpireTcpdumpArtifacts', enabled: true, prefix: 'tcpdump/', expiration: cdk.Duration.days(1), noncurrentVersionExpiration: cdk.Duration.days(2) },
      ],
      encryption: s3.BucketEncryption.KMS,
      encryptionKey: this.kmsKey,
      bucketKeyEnabled: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    };

    this.logsBucket = new s3.Bucket(this, 'LogsBucket', bucketProps);
    this.logsBucket.grantReadWrite(this.ssmAutomationRole);
    this.kmsKey.grantEncryptDecrypt(this.ssmAutomationRole);

    const uploadPrincipals: iam.IPrincipal[] = ecsInstanceRoleArns.map(
      arn => new iam.ArnPrincipal(arn),
    );

    // Add SSM Default Host Management role if provided
    if (props.ssmDefaultHostRoleArn) {
      uploadPrincipals.push(new iam.ArnPrincipal(props.ssmDefaultHostRoleArn));
    }

    this.logsBucket.addToResourcePolicy(new iam.PolicyStatement({
      sid: 'AllowEC2InstancesBucketPreflight',
      effect: iam.Effect.ALLOW,
      principals: uploadPrincipals,
      actions: ['s3:GetBucketPolicyStatus', 's3:GetBucketAcl', 's3:ListBucket'],
      resources: [this.logsBucket.bucketArn],
      conditions: { StringEquals: { 'aws:PrincipalAccount': cdk.Stack.of(this).account } },
    }));

    this.logsBucket.addToResourcePolicy(new iam.PolicyStatement({
      sid: 'AllowEC2InstancesUpload',
      effect: iam.Effect.ALLOW,
      principals: uploadPrincipals,
      actions: ['s3:PutObject'],
      resources: [`${this.logsBucket.bucketArn}/*`],
      conditions: { StringEquals: { 'aws:PrincipalAccount': cdk.Stack.of(this).account } },
    }));

    // ========================================================================
    // FINDINGS INDEXER LAMBDA (triggered by Unzip after extraction)
    // ========================================================================
    const findingsIndexerRole = new iam.Role(this, 'FindingsIndexerRole', {
      roleName: `${cdk.Stack.of(this).stackName}-findings-indexer-role`,
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')],
    });
    this.logsBucket.grantReadWrite(findingsIndexerRole);
    if (this.kmsKey) { this.kmsKey.grantEncryptDecrypt(findingsIndexerRole); }

    this.findingsIndexerFunction = new lambda.Function(this, 'FindingsIndexerFunction', {
      functionName: `${cdk.Stack.of(this).stackName}-findings-indexer`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'index.lambda_handler',
      role: findingsIndexerRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 1024,
      environment: { LOGS_BUCKET_NAME: this.logsBucket.bucketName },
      code: lambda.Code.fromInline(this.getFindingsIndexerCode()),
      logRetention: logs.RetentionDays.TWO_WEEKS,
    });

    // ========================================================================
    // UNZIP LAMBDA (triggers Findings Indexer after extraction)
    // ========================================================================
    const unzipLambdaRole = new iam.Role(this, 'UnzipLambdaRole', {
      roleName: `${cdk.Stack.of(this).stackName}-unzip-lambda-role`,
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')],
    });
    this.logsBucket.grantReadWrite(unzipLambdaRole);
    if (this.kmsKey) { this.kmsKey.grantEncryptDecrypt(unzipLambdaRole); }
    this.findingsIndexerFunction.grantInvoke(unzipLambdaRole);

    this.unzipFunction = new lambda.Function(this, 'UnzipFunction', {
      functionName: `${cdk.Stack.of(this).stackName}-unzip-function`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'index.lambda_handler',
      role: unzipLambdaRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 1024,
      environment: { FINDINGS_INDEXER_FUNCTION: this.findingsIndexerFunction.functionName },
      code: lambda.Code.fromInline(this.getUnzipLambdaCode()),
      logRetention: logs.RetentionDays.TWO_WEEKS,
    });

    this.logsBucket.addEventNotification(s3.EventType.OBJECT_CREATED, new s3n.LambdaDestination(this.unzipFunction), { suffix: '.zip' });
    this.logsBucket.addEventNotification(s3.EventType.OBJECT_CREATED, new s3n.LambdaDestination(this.unzipFunction), { suffix: '.tar.gz' });
    this.logsBucket.addEventNotification(s3.EventType.OBJECT_CREATED, new s3n.LambdaDestination(this.unzipFunction), { suffix: '.tgz' });

    // ========================================================================
    // SSM AUTOMATION LAMBDA
    // ========================================================================
    const lambdaExecutionRole = new iam.Role(this, 'LambdaExecutionRole', {
      roleName: `${cdk.Stack.of(this).stackName}-lambda-execution-role`,
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')],
    });

    const lambdaStartDocumentNames = requireCollectionApproval
      ? [collectApprovalDocName, batchApprovalDocName, tcpdumpApprovalDocName]
      : ['AWSSupport-CollectECSInstanceLogs'];
    const lambdaStartAutomationResources = allowedRegions.flatMap(region => [
      ...lambdaStartDocumentNames.flatMap(documentName => requireCollectionApproval
        ? [
          `arn:${partition}:ssm:${region}:${stack.account}:automation-definition/${documentName}:*`,
          `arn:${partition}:ssm:${region}:${stack.account}:document/${documentName}`,
        ]
        : [
          `arn:${partition}:ssm:${region}::automation-definition/${documentName}:*`,
          `arn:${partition}:ssm:${region}::document/${documentName}`,
        ]),
      `arn:${partition}:ssm:${region}:${stack.account}:automation-execution/*`,
    ]);

    lambdaExecutionRole.addToPolicy(new iam.PolicyStatement({
      sid: 'StartAllowedAutomationDocuments',
      effect: iam.Effect.ALLOW,
      actions: ['ssm:StartAutomationExecution'],
      resources: lambdaStartAutomationResources,
    }));

    lambdaExecutionRole.addToPolicy(new iam.PolicyStatement({
      sid: 'ReadAutomationExecutionStatus',
      effect: iam.Effect.ALLOW,
      actions: ['ssm:GetAutomationExecution'],
      resources: allowedRegions.map(
        region => `arn:${partition}:ssm:${region}:${stack.account}:automation-execution/*`,
      ),
    }));

    lambdaExecutionRole.addToPolicy(new iam.PolicyStatement({
      sid: 'RegionalSsmRead',
      effect: iam.Effect.ALLOW,
      actions: ['ssm:DescribeAutomationExecutions', 'ssm:DescribeInstanceInformation',
        'ssm:GetCommandInvocation'],
      resources: ['*'],
      conditions: requestedRegionCondition,
    }));

    lambdaExecutionRole.addToPolicy(new iam.PolicyStatement({
      sid: 'ReadAllowedAutomationDocuments',
      effect: iam.Effect.ALLOW,
      actions: ['ssm:GetDocument', 'ssm:DescribeDocument'],
      resources: allowedRegions.flatMap(region => lambdaStartDocumentNames.map(documentName =>
        requireCollectionApproval
          ? `arn:${partition}:ssm:${region}:${stack.account}:document/${documentName}`
          : `arn:${partition}:ssm:${region}::document/${documentName}`,
      )),
    }));

    lambdaExecutionRole.addToPolicy(new iam.PolicyStatement({
      sid: 'RegionalInfrastructureRead',
      effect: iam.Effect.ALLOW,
      actions: [
        'ec2:DescribeInstances', 'ec2:DescribeRegions',
        'ec2:DescribeInstanceStatus', 'ec2:DescribeNetworkInterfaces',
        'ec2:DescribeSubnets', 'ec2:DescribeSecurityGroups', 'ec2:DescribeRouteTables',
        'ecs:DescribeClusters',
        'ecs:DescribeContainerInstances', 'ecs:ListContainerInstances',
        'ecs:DescribeServices', 'ecs:ListServices',
        'ecs:DescribeTasks', 'ecs:ListTasks',
        'autoscaling:DescribeAutoScalingGroups',
      ],
      resources: ['*'],
      conditions: requestedRegionCondition,
    }));

    this.logsBucket.grantReadWrite(lambdaExecutionRole);
    if (this.kmsKey) { this.kmsKey.grantEncryptDecrypt(lambdaExecutionRole); }

    lambdaExecutionRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: ['iam:PassRole'],
      resources: [this.ssmAutomationRole.roleArn],
      conditions: { StringEquals: { 'iam:PassedToService': 'ssm.amazonaws.com' } },
    }));

    // Lambda cannot approve its own requests. Direct Run Command is available
    // only for the explicitly non-approval tcpdump path.
    if (!requireCollectionApproval && enabledRestrictedTools.includes('tcpdump_capture')) {
      lambdaExecutionRole.addToPolicy(new iam.PolicyStatement({
        sid: 'DirectTcpdumpRunShellScriptWithoutApproval',
        effect: iam.Effect.ALLOW,
        actions: ['ssm:SendCommand'],
        resources: runShellDocumentResources,
      }));
      lambdaExecutionRole.addToPolicy(new iam.PolicyStatement({
        sid: 'DirectTcpdumpInstancesWithoutApproval',
        effect: iam.Effect.ALLOW,
        actions: ['ssm:SendCommand'],
        resources: allowedInstanceResources,
      }));
    }

    this.collectionApprovalTopic = new sns.Topic(this, 'CollectionApprovalTopic', {
      topicName: `Automation-${cdk.Stack.of(this).stackName}-approvals`,
      displayName: 'ECS diagnostics collection approvals',
      masterKey: this.kmsKey,
    });
    for (const email of props.approvalNotificationEmails ?? []) {
      this.collectionApprovalTopic.addSubscription(new subscriptions.EmailSubscription(email));
    }
    this.collectionApprovalTopic.grantPublish(this.ssmAutomationRole);
    this.collectionApprovalTopic.grantPublish(lambdaExecutionRole);

    this.ssmAutomationRole.addToPolicy(new iam.PolicyStatement({
      sid: 'PassSelfToChildAutomations',
      effect: iam.Effect.ALLOW,
      actions: ['iam:PassRole'],
      resources: [this.ssmAutomationRole.roleArn],
      conditions: { StringEquals: { 'iam:PassedToService': 'ssm.amazonaws.com' } },
    }));

    if (requireCollectionApproval) {
      new ssm.CfnDocument(this, 'CollectApprovalDocument', {
      name: collectApprovalDocName,
      documentType: 'Automation',
      updateMethod: 'NewVersion',
      content: {
        schemaVersion: '0.3',
        description: 'Approve, then collect diagnostics from one ECS EC2 container instance.',
        assumeRole: this.ssmAutomationRole.roleArn,
        parameters: {
          ECSInstanceId: { type: 'String', allowedPattern: '^i-[0-9a-f]{8,17}$' },
          LogDestination: { type: 'String' },
        },
        mainSteps: [
          {
            name: 'waitForHumanApproval',
            action: 'aws:approve',
            timeoutSeconds: approvalTtlSeconds,
            onFailure: 'Abort',
            inputs: {
              NotificationArn: this.collectionApprovalTopic.topicArn,
              Message: 'Approve ECS instance log collection on {{ ECSInstanceId }}. Approval runs AWSSupport-CollectECSInstanceLogs and uploads the bundle to {{ LogDestination }}.',
              MinRequiredApprovals: 1,
              Approvers: approverArns,
            },
          },
          {
            name: 'collectLogs',
            action: 'aws:executeAutomation',
            inputs: {
              DocumentName: 'AWSSupport-CollectECSInstanceLogs',
              RuntimeParameters: {
                ECSInstanceId: '{{ ECSInstanceId }}',
                LogDestination: '{{ LogDestination }}',
                AutomationAssumeRole: this.ssmAutomationRole.roleArn,
              },
            },
          },
        ],
      },
    });

    new ssm.CfnDocument(this, 'BatchCollectApprovalDocument', {
      name: batchApprovalDocName,
      documentType: 'Automation',
      updateMethod: 'NewVersion',
      content: {
        schemaVersion: '0.3',
        description: 'Approve once, then collect diagnostics from up to 15 ECS EC2 container instances.',
        assumeRole: this.ssmAutomationRole.roleArn,
        parameters: {
          InstanceIds: { type: 'StringList', description: 'ECS EC2 container instance IDs (max 15)' },
          LogDestination: { type: 'String' },
        },
        mainSteps: [
          {
            name: 'waitForHumanApproval',
            action: 'aws:approve',
            timeoutSeconds: approvalTtlSeconds,
            onFailure: 'Abort',
            inputs: {
              NotificationArn: this.collectionApprovalTopic.topicArn,
              Message: 'Approve this batch ECS log collection. The execution Parameters list the ECS EC2 container instances; at most 15 child collections will start.',
              MinRequiredApprovals: 1,
              Approvers: approverArns,
            },
          },
          {
            name: 'fanOutCollections',
            action: 'aws:executeScript',
            timeoutSeconds: 600,
            inputs: {
              Runtime: 'python3.11',
              Handler: 'handler',
              InputPayload: {
                InstanceIds: '{{ InstanceIds }}',
                LogDestination: '{{ LogDestination }}',
              },
              Script: [
                'import boto3',
                '',
                'def handler(events, context):',
                '    ssm = boto3.client("ssm")',
                '    executions, errors = [], []',
                '    for instance_id in events["InstanceIds"][:15]:',
                '        try:',
                '            response = ssm.start_automation_execution(',
                '                DocumentName="AWSSupport-CollectECSInstanceLogs",',
                '                Parameters={',
                '                    "ECSInstanceId": [instance_id],',
                '                    "LogDestination": [events["LogDestination"]],',
                `                    "AutomationAssumeRole": ["${this.ssmAutomationRole.roleArn}"],`,
                '                },',
                '            )',
                '            executions.append(f"{instance_id}|{response[\'AutomationExecutionId\']}")',
                '        except Exception as error:',
                '            errors.append(f"{instance_id}|{error}")',
                '    return {"executions": executions, "errors": errors}',
              ].join('\n'),
            },
            outputs: [
              { Name: 'Executions', Selector: '$.Payload.executions', Type: 'StringList' },
              { Name: 'Errors', Selector: '$.Payload.errors', Type: 'StringList' },
            ],
          },
        ],
      },
    });

    new ssm.CfnDocument(this, 'TcpdumpApprovalDocument', {
      name: tcpdumpApprovalDocName,
      documentType: 'Automation',
      updateMethod: 'NewVersion',
      content: {
        schemaVersion: '0.3',
        description: 'Approve, then run a task-scoped tcpdump capture on an ECS EC2 container instance.',
        assumeRole: this.ssmAutomationRole.roleArn,
        parameters: {
          InstanceId: { type: 'String', allowedPattern: '^i-[0-9a-f]{8,17}$' },
          Commands: { type: 'String', description: 'Validated task-scoped capture script; review before approval' },
          ExecutionTimeoutSeconds: { type: 'String', allowedPattern: '^\\d{2,4}$', default: '240' },
          DurationSeconds: { type: 'String', allowedPattern: '^\\d{1,3}$' },
          Interface: { type: 'String', allowedPattern: '^[a-zA-Z0-9\\-\\.]+$' },
          BpfFilter: { type: 'String', allowedPattern: '^[^\\r\\n]{1,256}$' },
          CaptureScope: {
            type: 'String',
            allowedPattern: '^task/[0-9a-f]{32}/container/[A-Za-z0-9][A-Za-z0-9_.-]{0,254}$',
          },
        },
        mainSteps: [
          {
            name: 'waitForHumanApproval',
            action: 'aws:approve',
            timeoutSeconds: approvalTtlSeconds,
            onFailure: 'Abort',
            inputs: {
              NotificationArn: this.collectionApprovalTopic.topicArn,
              Message: 'Approve task-scoped tcpdump on ECS EC2 instance {{ InstanceId }} ({{ CaptureScope }}), interface {{ Interface }}, duration {{ DurationSeconds }}s, filter {{ BpfFilter }}. Review Commands before approving; packet contents may be sensitive.',
              MinRequiredApprovals: 1,
              Approvers: approverArns,
            },
          },
          {
            name: 'runTcpdump',
            action: 'aws:runCommand',
            inputs: {
              DocumentName: 'AWS-RunShellScript',
              InstanceIds: ['{{ InstanceId }}'],
              Parameters: {
                commands: ['{{ Commands }}'],
                executionTimeout: ['{{ ExecutionTimeoutSeconds }}'],
              },
              Comment: 'Human-approved task-scoped ECS tcpdump on {{ InstanceId }}',
            },
          },
        ],
      },
      });
    }

    const lambdaEnv: { [key: string]: string } = {
      LOGS_BUCKET_NAME: this.logsBucket.bucketName,
      SSM_AUTOMATION_ROLE_ARN: this.ssmAutomationRole.roleArn,
      ALLOWED_CLUSTER_NAMES: allowedClusterNames.join(','),
      ALLOWED_REGIONS: allowedRegions.join(','),
      PRESIGNED_URL_EXPIRATION_SECONDS: String(props.presignedUrlExpirationSeconds ?? 900),
      REQUIRE_COLLECTION_APPROVAL: String(requireCollectionApproval),
      APPROVAL_TOPIC_ARN: this.collectionApprovalTopic.topicArn,
      COLLECT_APPROVAL_DOCUMENT: requireCollectionApproval ? collectApprovalDocName : '',
      BATCH_APPROVAL_DOCUMENT: requireCollectionApproval ? batchApprovalDocName : '',
      TCPDUMP_APPROVAL_DOCUMENT: requireCollectionApproval ? tcpdumpApprovalDocName : '',
      APPROVAL_APPROVERS: approverArns.join(','),
      ENABLED_RESTRICTED_TOOLS: enabledRestrictedTools.join(','),
      PCAP_PRESIGNED_URL_EXPIRATION_SECONDS: String(props.pcapPresignedUrlExpirationSeconds ?? 60),
      MAX_PCAP_BYTES: String(props.maxPcapBytes ?? 209715200),
      APPROVAL_EMAILS_CONFIGURED: String((props.approvalNotificationEmails ?? []).length > 0),
    };
    if (this.kmsKey) { lambdaEnv['KMS_KEY_ARN'] = this.kmsKey.keyArn; }

    // SOP Bucket
    this.sopBucket = new s3.Bucket(this, 'SOPBucket', {
      bucketName: props.sopBucketName ?? `${cdk.Stack.of(this).stackName.toLowerCase()}-sops-${cdk.Stack.of(this).account}`,
      versioned: true,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });
    lambdaEnv['SOP_BUCKET_NAME'] = this.sopBucket.bucketName;
    this.sopBucket.grantRead(lambdaExecutionRole);

    // Auto-deploy SOP runbooks from local sops/ directory to the SOP bucket
    new s3deploy.BucketDeployment(this, 'SOPDeployment', {
      sources: [s3deploy.Source.asset(path.join(__dirname, '../', 'sops'))],
      destinationBucket: this.sopBucket,
      prune: true,
    });

    this.ssmAutomationFunction = new lambda.Function(this, 'SSMAutomationFunction', {
      functionName: `${cdk.Stack.of(this).stackName}-ssm-automation`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'ecs-log-automation.lambda_handler',
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 1024,
      environment: lambdaEnv,
      code: lambda.Code.fromAsset(path.join(__dirname, 'lambda')),
      logRetention: logs.RetentionDays.TWO_WEEKS,
    });

    // ========================================================================
    // GATEWAY EXECUTION ROLE
    // ========================================================================
    this.gatewayExecutionRole = new iam.Role(this, 'GatewayExecutionRole', {
      roleName: `${cdk.Stack.of(this).stackName}-gateway-execution-role`,
      assumedBy: new iam.ServicePrincipal('bedrock-agentcore.amazonaws.com'),
    });

    this.gatewayExecutionRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: ['lambda:InvokeFunction'],
      resources: [this.ssmAutomationFunction.functionArn],
    }));

    this.gatewayExecutionRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents'],
      resources: ['*'],
    }));

    this.ssmAutomationFunction.addPermission('AllowAgentCoreInvoke', {
      principal: new iam.ServicePrincipal('bedrock-agentcore.amazonaws.com'),
      action: 'lambda:InvokeFunction',
      sourceAccount: cdk.Stack.of(this).account,
    });

    // ========================================================================
    // COGNITO - Authentication
    // ========================================================================
    this.userPool = new cognito.UserPool(this, 'UserPool', {
      userPoolName: cognitoUserPoolName,
      passwordPolicy: { minLength: 8, requireUppercase: false, requireLowercase: false, requireDigits: false, requireSymbols: false },
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const resourceServer = new cognito.UserPoolResourceServer(this, 'ResourceServer', {
      userPool: this.userPool,
      identifier: resourceServerName,
      scopes: [
        { scopeName: 'gateway:read', scopeDescription: 'Read access to gateway' },
        { scopeName: 'gateway:write', scopeDescription: 'Write access to gateway' },
      ],
    });

    this.userPoolClient = new cognito.UserPoolClient(this, 'UserPoolClient', {
      userPool: this.userPool,
      userPoolClientName: 'ecs-log-gateway-client',
      generateSecret: true,
      oAuth: {
        flows: { clientCredentials: true },
        scopes: [
          cognito.OAuthScope.custom(`${resourceServerName}/gateway:read`),
          cognito.OAuthScope.custom(`${resourceServerName}/gateway:write`),
        ],
      },
      supportedIdentityProviders: [cognito.UserPoolClientIdentityProvider.COGNITO],
    });
    this.userPoolClient.node.addDependency(resourceServer);

    const userPoolDomain = new cognito.UserPoolDomain(this, 'UserPoolDomain', {
      userPool: this.userPool,
      cognitoDomain: { domainPrefix: `${cdk.Stack.of(this).stackName.toLowerCase()}-${cdk.Stack.of(this).account}` },
    });

    // ========================================================================
    // AGENTCORE GATEWAY
    // ========================================================================
    const gateway = new cdk.CfnResource(this, 'AgentCoreGateway', {
      type: 'AWS::BedrockAgentCore::Gateway',
      properties: {
        Name: gatewayName,
        Description: 'ECS Instance Log Collection MCP Server with pre-indexed findings, byte-range streaming, and incident analysis',
        ProtocolType: 'MCP',
        AuthorizerType: 'CUSTOM_JWT',
        AuthorizerConfiguration: {
          CustomJWTAuthorizer: {
            AllowedClients: [this.userPoolClient.userPoolClientId],
            DiscoveryUrl: `https://cognito-idp.${cdk.Stack.of(this).region}.amazonaws.com/${this.userPool.userPoolId}/.well-known/openid-configuration`,
          },
        },
        RoleArn: this.gatewayExecutionRole.roleArn,
      },
    });
    gateway.node.addDependency(this.userPoolClient);
    gateway.node.addDependency(userPoolDomain);

    const gatewayTarget = new cdk.CfnResource(this, 'LambdaGatewayTarget', {
      type: 'AWS::BedrockAgentCore::GatewayTarget',
      properties: {
        GatewayIdentifier: gateway.ref,
        Name: 'ECSInstanceLogTarget',
        Description: 'ECS Instance Log Collection Target',
        TargetConfiguration: {
          Mcp: {
            Lambda: {
              LambdaArn: this.ssmAutomationFunction.functionArn,
              ToolSchema: { InlinePayload: this.getToolSchemaDefinitions(enabledRestrictedTools) },
            },
          },
        },
        CredentialProviderConfigurations: [{ CredentialProviderType: 'GATEWAY_IAM_ROLE' }],
      },
    });
    gatewayTarget.node.addDependency(this.ssmAutomationFunction);
    gatewayTarget.node.addDependency(this.gatewayExecutionRole);

    // ========================================================================
    // OUTPUTS
    // ========================================================================
    new cdk.CfnOutput(this, 'GatewayId', { description: 'ID of the AgentCore Gateway', value: gateway.ref, exportName: `${cdk.Stack.of(this).stackName}-GatewayId` });
    new cdk.CfnOutput(this, 'GatewayUrl', { description: 'MCP Server URL', value: gateway.getAtt('GatewayUrl').toString(), exportName: `${cdk.Stack.of(this).stackName}-GatewayUrl` });
    new cdk.CfnOutput(this, 'CognitoUserPoolId', { description: 'Cognito User Pool ID', value: this.userPool.userPoolId, exportName: `${cdk.Stack.of(this).stackName}-CognitoUserPoolId` });
    new cdk.CfnOutput(this, 'CognitoClientId', { description: 'OAuth Client ID', value: this.userPoolClient.userPoolClientId, exportName: `${cdk.Stack.of(this).stackName}-CognitoClientId` });
    new cdk.CfnOutput(this, 'OAuthExchangeUrl', { description: 'OAuth Token URL', value: `https://${cdk.Stack.of(this).stackName.toLowerCase()}-${cdk.Stack.of(this).account}.auth.${cdk.Stack.of(this).region}.amazoncognito.com/oauth2/token`, exportName: `${cdk.Stack.of(this).stackName}-OAuthExchangeUrl` });
    new cdk.CfnOutput(this, 'OAuthScope', { description: 'OAuth Scope', value: `${resourceServerName}/gateway:read`, exportName: `${cdk.Stack.of(this).stackName}-OAuthScope` });
    new cdk.CfnOutput(this, 'LogsBucketName', { description: 'S3 bucket for collected logs', value: this.logsBucket.bucketName, exportName: `${cdk.Stack.of(this).stackName}-LogsBucketName` });
    new cdk.CfnOutput(this, 'SSMAutomationRoleArn', { description: 'SSM Automation Role ARN', value: this.ssmAutomationRole.roleArn, exportName: `${cdk.Stack.of(this).stackName}-SSMAutomationRoleArn` });
    new cdk.CfnOutput(this, 'CollectionApprovalTopicArn', { description: 'SNS topic for native SSM approval notifications', value: this.collectionApprovalTopic.topicArn });
    new cdk.CfnOutput(this, 'CollectionApprovalDocuments', { description: 'Native SSM approval wrapper documents', value: `${collectApprovalDocName},${batchApprovalDocName},${tcpdumpApprovalDocName}` });
    if (this.kmsKey) { new cdk.CfnOutput(this, 'EncryptionKeyArn', { description: 'KMS Encryption Key ARN', value: this.kmsKey.keyArn, exportName: `${cdk.Stack.of(this).stackName}-EncryptionKeyArn` }); }
    new cdk.CfnOutput(this, 'SOPBucketName', { description: 'S3 bucket for Standard Operating Procedures', value: this.sopBucket.bucketName, exportName: `${cdk.Stack.of(this).stackName}-SOPBucketName` });
  }

  private getToolSchemaDefinitions(enabledRestrictedTools: string[]): object[] {
    const tools: Array<{ Name: string; [key: string]: unknown }> = [
      // =====================================================================
      // TIER 1: CORE OPERATIONS
      // =====================================================================
      {
        Name: 'collect',
        Description: 'Start ECS log collection from an EC2-backed container instance. Collection may be approval-gated: status="pending_approval" means the SSM Automation is paused at native human approval. Show approvalConsoleUrl and poll status(executionId); do not call collect again because collection starts automatically after approval. Supports idempotency and cross-region execution. CITATION: Cite executionId and region.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The EC2 instance ID of the ECS container instance (e.g., i-0123456789abcdef0)' },
            idempotencyToken: { Type: 'string', Description: 'Optional token to prevent duplicate executions. If provided and a matching execution exists, returns the existing executionId.' },
            region: { Type: 'string', Description: 'AWS region where the instance runs (e.g., us-west-2). Optional: auto-detected from instance if omitted.' },
          },
          Required: ['instanceId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            executionId: { Type: 'string', Description: 'SSM Automation execution ID for polling' },
            instanceId: { Type: 'string' },
            region: { Type: 'string' },
            status: { Type: 'string', Description: 'pending_approval | in_progress | completed | failed' },
            approvalConsoleUrl: { Type: 'string', Description: 'Systems Manager console link when status is pending_approval' },
            humanApproval: { Type: 'object', Description: 'Human approval state and console URL' },
            estimatedCompletionTime: { Type: 'string' },
            idempotent: { Type: 'boolean', Description: 'True if returning existing execution' },
            task: { Type: 'object', Description: 'Async task envelope for polling', Properties: { taskId: { Type: 'string' }, state: { Type: 'string', Description: 'running|completed|failed|cancelled' }, message: { Type: 'string' }, progress: { Type: 'integer', Description: '0-100 percent' } } },
          },
        },
      },
      {
        Name: 'status',
        Description: 'Get detailed status of a log collection execution including progress percentage, step details, and failure reasons. Automatically resolves the region where the execution was started. CITATION: Always cite executionId and status in your response.',
        InputSchema: {
          Type: 'object',
          Properties: {
            executionId: { Type: 'string', Description: 'The SSM Automation execution ID returned from collect' },
            includeStepDetails: { Type: 'boolean', Description: 'Include individual step status (default: true)' },
            region: { Type: 'string', Description: 'AWS region of the execution. Optional: auto-resolved from stored execution metadata if omitted.' },
          },
          Required: ['executionId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            automation: { Type: 'object', Properties: { executionId: { Type: 'string' }, status: { Type: 'string', Description: 'InProgress|Success|Failed|Cancelled' }, progress: { Type: 'integer' }, failureReason: { Type: 'string' }, stepDetails: { Type: 'array' } } },
            task: { Type: 'object', Properties: { taskId: { Type: 'string' }, state: { Type: 'string' }, message: { Type: 'string' }, progress: { Type: 'integer' } } },
          },
        },
      },
      {
        Name: 'validate',
        Description: 'Verify all expected files were extracted from the log bundle. Returns manifest with file counts, sizes, and missing patterns. Uses manifest.json when available for authoritative file inventory. CITATION: Cite fileCount, totalSizeHuman, and any missingPatterns.',
        InputSchema: {
          Type: 'object',
          Properties: {
            executionId: { Type: 'string', Description: 'SSM execution ID to validate' },
            instanceId: { Type: 'string', Description: 'Alternative: Instance ID to locate bundle' },
          },
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            complete: { Type: 'boolean' }, fileCount: { Type: 'integer' }, totalSize: { Type: 'integer' }, totalSizeHuman: { Type: 'string' },
            missingPatterns: { Type: 'array' }, foundPatterns: { Type: 'array' }, hasFindingsIndex: { Type: 'boolean' },
            manifest: { Type: 'array', Description: 'File list with key, fullKey, size, sizeHuman' },
          },
        },
      },
      {
        Name: 'errors',
        Description: 'Get pre-indexed error findings (fast path). Returns categorized errors by severity with finding_ids for citation. Each finding has a stable finding_id (F-001 format). Automatically recommends relevant SOPs based on detected error patterns (recommendedSOPs field). CITATION: Always cite finding_id and severity when referencing findings. Use finding_ids with summarize tool.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The EC2 instance ID to get error summary for' },
            severity: { Type: 'string', Description: 'Filter by severity: critical, high, medium, low, info, or all (default: all). Legacy "warning" maps to "high".' },
            response_format: { Type: 'string', Description: '"concise" (default) returns finding_id/severity/pattern/file/count only. "detailed" includes full sample text and line numbers.' },
            pageSize: { Type: 'integer', Description: 'Number of findings per page (default: 50, max: 200)' },
            pageToken: { Type: 'string', Description: 'Opaque token for next page (from previous response nextPageToken)' },
            clusterContext: { Type: 'string', Description: 'ECS cluster name for baseline subtraction. When provided, findings seen 10+ times are annotated as baseline (normal operation).' },
          },
          Required: ['instanceId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string' },
            findings: { Type: 'array', Description: 'Array of findings with finding_id, severity, pattern, file, count' },
            totalFindings: { Type: 'integer' },
            summary: { Type: 'object', Description: 'Counts by severity: critical, high, medium, low, info' },
            hasMore: { Type: 'boolean' }, nextPageToken: { Type: 'string' },
            coverage_report: { Type: 'object', Description: 'files_scanned, files_skipped, scan_complete' },
            recommendedSOPs: { Type: 'array', Description: 'Auto-matched SOP runbooks based on detected error patterns. Each entry has sopName, relevanceScore, matchedKeywords, reason. Use get_sop to retrieve full SOP content.' },
          },
        },
      },
      {
        Name: 'read',
        Description: 'Read a chunk of a log file using byte-range streaming. NO TRUNCATION. Supports both byte-range and line-based reading for multi-GB files. Line-aligned: byte reads snap to newline boundaries. CITATION: Cite logKey, startByte, endByte, and totalSize.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The ECS EC2 instance that owns this log object' },
            logKey: { Type: 'string', Description: 'The canonical S3 key below ecs_{instanceId}/ (from validate manifest)' },
            startByte: { Type: 'integer', Description: 'Starting byte offset (default: 0). Snaps forward to next newline.' },
            endByte: { Type: 'integer', Description: 'Ending byte offset (default: startByte + 1MB). Snaps forward to next newline.' },
            startLine: { Type: 'integer', Description: 'Alternative: Starting line number (1-based)' },
            lineCount: { Type: 'integer', Description: 'Number of lines to return when using startLine (default: 1000)' },
          },
          Required: ['instanceId', 'logKey'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            logKey: { Type: 'string' }, content: { Type: 'string' },
            startByte: { Type: 'integer' }, endByte: { Type: 'integer' }, totalSize: { Type: 'integer' },
            hasMore: { Type: 'boolean' }, nextChunkToken: { Type: 'string' },
            truncated: { Type: 'boolean', Description: 'Always false — never truncates' },
            lineAligned: { Type: 'boolean' },
          },
        },
      },
      // =====================================================================
      // TIER 2: ADVANCED ANALYSIS
      // =====================================================================
      {
        Name: 'search',
        Description: 'Full-text regex search across all logs without truncation. Use for detailed investigation after reviewing error summary. CITATION: Cite finding_id (S-NNN format), file name, and match count for each result group.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The EC2 instance ID to search logs for' },
            query: { Type: 'string', Description: 'Regex pattern to search for (e.g., "CannotPullContainerError|ResourceInitializationError")' },
            logTypes: { Type: 'string', Description: 'Comma-separated log types to search. Available types: ecs-agent, docker, containers, system, dmesg, networking, cgroups, metadata, gpu (default: all)' },
            maxResults: { Type: 'integer', Description: 'Maximum results per file (default: 100, max: 500)' },
            response_format: { Type: 'string', Description: '"concise" (default) or "detailed"' },
          },
          Required: ['instanceId', 'query'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string' }, query: { Type: 'string' },
            filesSearched: { Type: 'integer' }, filesWithMatches: { Type: 'integer' }, totalMatches: { Type: 'integer' },
            results: { Type: 'array', Description: 'Array of {finding_id, file, fullKey, matchCount, matches[]}' },
            coverage_report: { Type: 'object' },
          },
        },
      },
      {
        Name: 'correlate',
        Description: 'Cross-file timeline correlation for incident analysis. Groups events by component, builds temporal clusters, and identifies potential root cause chains. Automatically recommends relevant SOPs based on correlated findings (recommendedSOPs field). CITATION: Cite finding_ids, confidence level, and any gaps reported.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The EC2 instance ID to correlate events for' },
            timeWindow: { Type: 'integer', Description: 'Seconds around pivot event (default: 60)' },
            pivotEvent: { Type: 'string', Description: 'Event to correlate around (optional)' },
            components: { Type: 'array', Description: 'Components to include (optional)' },
            response_format: { Type: 'string', Description: '"concise" (default) or "detailed"' },
          },
          Required: ['instanceId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string' }, timeline: { Type: 'array' }, byComponent: { Type: 'object' },
            correlations: { Type: 'array' }, temporal_clusters: { Type: 'array' },
            potential_root_cause_chain: { Type: 'array' },
            confidence: { Type: 'string', Description: 'high|medium|low|none' },
            gaps: { Type: 'array' }, coverage_report: { Type: 'object' },
            recommendedSOPs: { Type: 'array', Description: 'Auto-matched SOP runbooks based on correlated findings. Each entry has sopName, relevanceScore, matchedKeywords, reason.' },
          },
        },
      },
      {
        Name: 'artifact',
        Description: 'Get secure presigned URL for large artifacts. Use for files too large to return directly. CITATION: Cite the logKey and expiresAt timestamp.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The ECS EC2 instance that owns this artifact' },
            logKey: { Type: 'string', Description: 'The canonical S3 key below ecs_{instanceId}/; tcpdump and metadata keys are rejected' },
            expirationMinutes: { Type: 'integer', Description: 'Positive URL lifetime request, capped by deployment PRESIGNED_URL_EXPIRATION' },
          },
          Required: ['instanceId', 'logKey'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            logKey: { Type: 'string' }, presignedUrl: { Type: 'string' }, expiresAt: { Type: 'string' }, sizeHuman: { Type: 'string' },
          },
        },
      },
      {
        Name: 'summarize',
        Description: 'Generate structured incident summary grounded in indexed findings. Pass finding_ids from errors tool to constrain summary to specific findings. Output includes grounded flag (true = all claims backed by finding_ids). Automatically recommends relevant SOPs based on findings and triage category (recommendedSOPs field). CITATION: Always cite the finding_ids that support each claim.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The EC2 instance ID to summarize' },
            includeRecommendations: { Type: 'boolean', Description: 'Include remediation suggestions (default: true)' },
            finding_ids: { Type: 'array', Description: 'Optional list of finding_ids (F-001 format) from errors tool. When provided, summary is constrained to only these findings.' },
          },
          Required: ['instanceId', 'finding_ids'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string' }, grounded: { Type: 'boolean' },
            unresolvedFindingIds: { Type: 'array' }, criticalFindings: { Type: 'array' },
            highFindings: { Type: 'array' }, affectedComponents: { Type: 'array' },
            recommendations: { Type: 'array' }, confidence: { Type: 'string' }, gaps: { Type: 'array' },
            recommendedSOPs: { Type: 'array', Description: 'Auto-matched SOP runbooks based on findings and triage category. Each entry has sopName, relevanceScore, matchedKeywords, reason. Use get_sop to retrieve full SOP content.' },
          },
        },
      },
      {
        Name: 'history',
        Description: 'List historical log collections for audit and comparison. Supports cross-region listing. CITATION: Cite executionId and status for each entry.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'Filter by instance ID (optional)' },
            maxResults: { Type: 'integer', Description: 'Maximum results (default: 20, max: 50)' },
            status: { Type: 'string', Description: 'Filter by status: Success, Failed, InProgress (optional)' },
            region: { Type: 'string', Description: 'AWS region to list executions from (default: Lambda region).' },
          },
        },
        OutputSchema: {
          Type: 'object',
          Properties: { executions: { Type: 'array' }, totalCount: { Type: 'integer' } },
        },
      },
      // =====================================================================
      // TIER 3: CLUSTER-LEVEL INTELLIGENCE
      // =====================================================================
      {
        Name: 'cluster_health',
        Description: 'Get a comprehensive health overview of an ECS cluster. Enumerates all container instances, checks SSM agent status, instance metadata (type, AZ, AMI, launch time), ECS agent connectivity, and flags unhealthy instances. The entry point before diving into individual instance investigation. CITATION: Cite clusterName, instance counts, and any unhealthy instanceIds.',
        InputSchema: {
          Type: 'object',
          Properties: {
            clusterName: { Type: 'string', Description: 'Name of the ECS cluster to inspect' },
            region: { Type: 'string', Description: 'AWS region of the cluster (auto-detected if omitted)' },
            includeSSMStatus: { Type: 'boolean', Description: 'Check SSM agent connectivity for each instance (default: true)' },
          },
          Required: ['clusterName'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            clusterName: { Type: 'string' }, totalInstances: { Type: 'integer' },
            healthyInstances: { Type: 'integer' }, unhealthyInstances: { Type: 'integer' },
            instances: { Type: 'array' },
          },
        },
      },
      {
        Name: 'compare_instances',
        Description: 'Diff error findings and health status between two or more container instances. Surfaces what is unique to a failing instance vs. common across all instances. CITATION: Cite instanceIds compared and unique findings per instance.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceIds: { Type: 'array', Description: 'List of 2+ EC2 instance IDs to compare (e.g., ["i-aaa", "i-bbb"])' },
            compareFields: { Type: 'string', Description: 'What to compare: "errors", "config", "all" (default: "all")' },
          },
          Required: ['instanceIds'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            commonFindings: { Type: 'array' }, uniqueFindings: { Type: 'object' }, insight: { Type: 'string' },
          },
        },
      },
      {
        Name: 'batch_collect',
        Description: 'Smart batch ECS log collection with statistical sampling. Defaults to a DRY RUN; pass dryRun=false to collect from at most 15 instances. Real collection may return status="pending_approval" and pause once for native human approval before automatically fanning out child collections. Show approvalConsoleUrl and poll batch_status(batchId); do not call batch_collect again. CITATION: Cite batchId, instance count, and sampling strategy.',
        InputSchema: {
          Type: 'object',
          Properties: {
            clusterName: { Type: 'string', Description: 'Name of the ECS cluster' },
            region: { Type: 'string', Description: 'AWS region of the cluster (auto-detected if omitted)' },
            filter: { Type: 'string', Description: 'Instance filter: "all", "unhealthy", "disconnected" (default: "unhealthy")' },
            strategy: { Type: 'string', Description: '"sample" for smart sampling or "all" to collect from every filtered instance (default: "sample")' },
            samplesPerBucket: { Type: 'integer', Description: 'Instances to sample per failure bucket (default: 3, max: 5)' },
            maxTotalCollections: { Type: 'integer', Description: 'Hard cap on total collections (default: 15, max: 15)' },
            groupBy: { Type: 'string', Description: 'Grouping strategy: "auto", "az", "instance-type", "ami" (default: "auto")' },
            dryRun: { Type: 'boolean', Description: 'Preview which instances would be collected without starting (default: true). Set false to collect.' },
          },
          Required: ['clusterName'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            batchId: { Type: 'string' }, executions: { Type: 'array' },
            status: { Type: 'string', Description: 'dry_run | pending_approval | in_progress | completed | failed' },
            approvalConsoleUrl: { Type: 'string', Description: 'Systems Manager console link when status is pending_approval' },
            humanApproval: { Type: 'object', Description: 'Human approval state and console URL' },
            totalInstances: { Type: 'integer' }, sampledInstances: { Type: 'integer' }, strategy: { Type: 'string' },
            task: { Type: 'object', Properties: { taskId: { Type: 'string' }, state: { Type: 'string' }, message: { Type: 'string' }, progress: { Type: 'integer' } } },
          },
        },
      },
      {
        Name: 'batch_status',
        Description: 'Poll status of multiple log collections at once. Returns consolidated view with allComplete boolean. Use after batch_collect to wait for all collections to finish. CITATION: Cite allComplete status and any failed executionIds.',
        InputSchema: {
          Type: 'object',
          Properties: {
            batchId: { Type: 'string', Description: 'Batch ID returned by batch_collect' },
          },
          Required: ['batchId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            allComplete: { Type: 'boolean' }, executions: { Type: 'array' },
            successCount: { Type: 'integer' }, failedCount: { Type: 'integer' }, inProgressCount: { Type: 'integer' },
          },
        },
      },
      {
        Name: 'network_diagnostics',
        Description: 'Extract and structure networking info from collected log bundles. Parses iptables rules, Docker networking, route tables, DNS resolution, ENI attachment status, and security group config. Returns structured data instead of raw text. Automatically recommends relevant SOPs based on detected networking issues (recommendedSOPs field). CITATION: Cite instanceId and each section analyzed.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The EC2 instance ID to analyze networking for' },
            region: { Type: 'string', Description: 'Allowed AWS region used for live ENI and security-group sections' },
            sections: { Type: 'string', Description: 'Comma-separated sections: "iptables,docker,routes,dns,eni,security-groups" or "all" (default: "all")' },
          },
          Required: ['instanceId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string' }, sections: { Type: 'object' },
            assessment: { Type: 'string' }, issues: { Type: 'array' },
            confidence: { Type: 'string' }, gaps: { Type: 'array' },
            recommendedSOPs: { Type: 'array', Description: 'Auto-matched SOP runbooks based on detected networking issues. Each entry has sopName, relevanceScore, matchedKeywords, reason.' },
          },
        },
      },
      // =====================================================================
      // TIER 4: LIVE PACKET CAPTURE
      // =====================================================================
      {
        Name: 'tcpdump_capture',
        Description: 'Start or poll a human-approved, task-scoped tcpdump capture on an ECS EC2 container instance. taskId and confirmCapture=true are required. Fargate, host-network, and host-wide captures are rejected, and the tool never installs tcpdump. When approval is enabled, show approvalConsoleUrl and poll with executionId; do not submit another capture. CITATION: Cite executionId or commandId, instanceId, and taskId.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'EC2 instance ID of the ECS container instance hosting the target task' },
            taskId: { Type: 'string', Description: 'Exact ECS task ID or full task ARN (required; ECS EC2 launch type only)' },
            containerName: { Type: 'string', Description: 'Exact RUNNING application container name. May be omitted only when exactly one eligible container exists; ambiguous tasks fail closed.' },
            durationSeconds: { Type: 'integer', Description: 'Capture duration in seconds (default: 120, max: 300)' },
            interface: { Type: 'string', Description: 'Network interface inside the task namespace (default: "any")' },
            filter: { Type: 'string', Description: 'Restricted BPF filter expression (for example "port 443" or "host 10.0.0.1")' },
            confirmCapture: { Type: 'boolean', Description: 'Must be true to request a new task-scoped packet capture' },
            commandId: { Type: 'string', Description: 'SSM Command UUID from an approved running capture; provide it to poll Run Command status' },
            executionId: { Type: 'string', Description: 'SSM Automation execution ID from a pending_approval response; provide it to poll approval status' },
            region: { Type: 'string', Description: 'AWS region where the ECS EC2 container instance runs (optional; auto-detected)' },
          },
          Required: ['instanceId', 'taskId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            commandId: { Type: 'string', Description: 'SSM Command ID once the approved capture starts' },
            executionId: { Type: 'string', Description: 'Approval-gated SSM Automation execution ID' },
            approvalConsoleUrl: { Type: 'string', Description: 'Systems Manager console link for human approval' },
            humanApproval: { Type: 'object', Description: 'Human approval state and console URL' },
            instanceId: { Type: 'string' },
            taskId: { Type: 'string' },
            status: { Type: 'string', Description: 'pending_approval | in_progress | completed | failed' },
            s3Key: { Type: 'string' },
            s3KeyTxt: { Type: 'string' },
            s3KeyStats: { Type: 'string' },
            s3Bucket: { Type: 'string' },
            presignedUrl: { Type: 'string', Description: 'Short-lived pcap download URL' },
            fileSizeBytes: { Type: 'integer' },
            task: { Type: 'object', Properties: { taskId: { Type: 'string' }, state: { Type: 'string' }, message: { Type: 'string' }, progress: { Type: 'integer' } } },
          },
        },
      },
      {
        Name: 'tcpdump_analyze',
        Description: 'Analyze a completed task-scoped tcpdump capture from an ECS EC2 task using its exact commandId. Returns decoded packets, protocol statistics, top talkers, and anomaly detection. This tool does not initiate captures and is unavailable unless explicitly enabled. CITATION: Cite commandId, instanceId, task scope, and anomalies.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'EC2 instance ID (required)' },
            commandId: { Type: 'string', Description: 'SSM Command UUID returned by tcpdump_capture (required; no latest-capture fallback)' },
            section: { Type: 'string', Description: '"summary" (decoded packets), "stats" (protocol breakdown), "all" (default: "all")' },
            maxPackets: { Type: 'integer', Description: 'Max decoded packet lines to return (default: 500, max: 3000)' },
            filter: { Type: 'string', Description: 'Text filter on decoded lines (e.g., "SYN", "RST", "10.0.0.5")' },
          },
          Required: ['instanceId', 'commandId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string' },
            commandId: { Type: 'string' },
            captureInfo: { Type: 'object' },
            statistics: { Type: 'object', Description: 'Protocol breakdown, port distribution, TCP flags, top talkers' },
            anomalies: { Type: 'array', Description: 'Detected anomalies with type, severity, and message' },
            decodedPackets: { Type: 'object', Description: 'Decoded packet lines with totalPackets, returnedPackets, truncated flag' },
            pcapDownloadUrl: { Type: 'string', Description: 'Short-lived presigned URL to download the raw pcap file' },
          },
        },
      },
      // =====================================================================
      // SOP MANAGEMENT TOOLS
      // =====================================================================
      {
        Name: 'list_sops',
        Description: 'List all available Standard Operating Procedures (SOPs) in the S3 bucket. Returns name, size, and last modified date for each SOP.',
        InputSchema: {
          Type: 'object',
          Properties: {},
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            sops: { Type: 'array', Description: 'Array of {name, size, lastModified}' },
            count: { Type: 'integer' },
            bucket: { Type: 'string' },
          },
        },
      },
      {
        Name: 'get_sop',
        Description: 'Get a specific Standard Operating Procedure (SOP) by name. Returns the full content of the SOP file. Use list_sops first to discover available SOPs.',
        InputSchema: {
          Type: 'object',
          Properties: {
            sopName: {
              Type: 'string',
              Description: 'The name/key of the SOP file to retrieve (e.g., "runbooks/pod-crashloop.md")',
            },
          },
          Required: ['sopName'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            sop: { Type: 'object', Description: '{name, content, size, lastModified, contentType}' },
          },
        },
      },
    ];

    return tools.filter(tool =>
      !['tcpdump_capture', 'tcpdump_analyze'].includes(tool.Name)
      || enabledRestrictedTools.includes(tool.Name),
    );
  }

  private getUnzipLambdaCode(): string {
    return `
import json
import boto3
import zipfile
import tarfile
import io
import os
import re
from urllib.parse import unquote_plus
from datetime import datetime

s3_client = boto3.client('s3')
lambda_client = boto3.client('lambda')

FINDINGS_INDEXER_FUNCTION = os.environ.get('FINDINGS_INDEXER_FUNCTION', '')

def get_content_type(file_name):
    if file_name.endswith('.log') or file_name.endswith('.txt'):
        return 'text/plain'
    elif file_name.endswith('.json'):
        return 'application/json'
    elif file_name.endswith('.yaml') or file_name.endswith('.yml'):
        return 'text/yaml'
    return 'application/octet-stream'

def sanitize_archive_path(file_name):
    normalized = os.path.normpath(file_name)
    if normalized.startswith('..') or '/../' in normalized or normalized.startswith('/'):
        print(f"SECURITY: Skipping suspicious archive path: {file_name}")
        return None
    return normalized.lstrip('./')

MANAGED_BUNDLE_RE = re.compile(
    r'^ecs_(i-[0-9a-f]{8,17})_([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\\.(zip|tar\\.gz|tgz)$',
    re.IGNORECASE,
)
CANONICAL_BUNDLE_RE = re.compile(
    r'^(ecs_(i-[0-9a-f]{8,17})/[A-Za-z0-9_.-]+)\\.(zip|tar\\.gz|tgz)$',
    re.IGNORECASE,
)

def resolve_extract_prefix(key):
    managed_match = MANAGED_BUNDLE_RE.fullmatch(key)
    if managed_match:
        instance_id, execution_id = managed_match.group(1), managed_match.group(2)
        return f"ecs_{instance_id}/{execution_id}/extracted/"
    canonical_match = CANONICAL_BUNDLE_RE.fullmatch(key)
    if canonical_match:
        return f"{canonical_match.group(1)}/extracted/"
    return None

def extract_zip(bucket, key, content, extract_prefix):
    extracted_files = []
    with zipfile.ZipFile(io.BytesIO(content), 'r') as zip_ref:
        for file_info in zip_ref.infolist():
            if file_info.is_dir():
                continue
            file_name = sanitize_archive_path(file_info.filename)
            if file_name is None:
                continue
            file_content = zip_ref.read(file_info.filename)
            extract_key = f"{extract_prefix}{file_name}"
            s3_client.put_object(Bucket=bucket, Key=extract_key, Body=file_content, ContentType=get_content_type(file_name))
            extracted_files.append(extract_key)
            print(f"Extracted: {extract_key}")
    return extracted_files, extract_prefix

def extract_targz(bucket, key, content, extract_prefix):
    extracted_files = []
    with tarfile.open(fileobj=io.BytesIO(content), mode='r:gz') as tar_ref:
        for member in tar_ref.getmembers():
            if not member.isfile():
                continue
            file_name = sanitize_archive_path(member.name)
            if file_name is None:
                continue
            file_obj = tar_ref.extractfile(member)
            if file_obj is None:
                continue
            file_content = file_obj.read()
            extract_key = f"{extract_prefix}{file_name}"
            s3_client.put_object(Bucket=bucket, Key=extract_key, Body=file_content, ContentType=get_content_type(file_name))
            extracted_files.append(extract_key)
            print(f"Extracted: {extract_key}")
    return extracted_files, extract_prefix

def trigger_findings_indexer(bucket, prefix, file_count):
    if not FINDINGS_INDEXER_FUNCTION:
        print("No findings indexer function configured, skipping")
        return
    try:
        lambda_client.invoke(FunctionName=FINDINGS_INDEXER_FUNCTION, InvocationType='Event', Payload=json.dumps({'bucket': bucket, 'prefix': prefix, 'fileCount': file_count}))
        print(f"Triggered findings indexer for prefix: {prefix}")
    except Exception as e:
        print(f"Failed to trigger findings indexer: {str(e)}")

def generate_manifest(bucket, prefix, extracted_files, archive_key, archive_size):
    try:
        file_details = []
        for file_key in extracted_files:
            try:
                head = s3_client.head_object(Bucket=bucket, Key=file_key)
                relative_path = file_key.split('/extracted/')[-1] if '/extracted/' in file_key else file_key
                file_details.append({'key': relative_path, 'fullKey': file_key, 'size': head['ContentLength'], 'contentType': head.get('ContentType', 'application/octet-stream')})
            except Exception:
                file_details.append({'key': file_key.split('/extracted/')[-1] if '/extracted/' in file_key else file_key, 'fullKey': file_key, 'size': 0, 'contentType': 'unknown'})
        manifest = {'version': 2, 'generatedAt': datetime.utcnow().isoformat() + 'Z', 'archiveKey': archive_key, 'archiveSize': archive_size, 'totalFiles': len(extracted_files), 'totalSize': sum(f['size'] for f in file_details), 'files': file_details}
        manifest_key = f"{prefix}manifest.json"
        s3_client.put_object(Bucket=bucket, Key=manifest_key, Body=json.dumps(manifest, default=str), ContentType='application/json')
        print(f"Wrote manifest.json to {manifest_key} ({len(extracted_files)} files)")
    except Exception as e:
        print(f"Warning: Failed to generate manifest.json: {str(e)}")

def cleanup_old_bundles(bucket, current_archive_key, max_bundles_to_keep=2):
    """Delete old managed-runbook bundles for the same instance."""
    try:
        current_match = MANAGED_BUNDLE_RE.fullmatch(current_archive_key)
        if not current_match:
            print(f"Archive is not a managed-runbook root bundle: {current_archive_key}; skipping cleanup")
            return
        instance_id = current_match.group(1)
        bundle_prefix = f"ecs_{instance_id}_"
        paginator = s3_client.get_paginator('list_objects_v2')
        archives = []
        for page in paginator.paginate(Bucket=bucket, Prefix=bundle_prefix):
            for obj in page.get('Contents', []):
                match = MANAGED_BUNDLE_RE.fullmatch(obj['Key'])
                if match and match.group(1).lower() == instance_id.lower():
                    archives.append({
                        'key': obj['Key'],
                        'execution_id': match.group(2),
                        'last_modified': obj['LastModified'],
                    })
        if len(archives) <= max_bundles_to_keep:
            print(f"Only {len(archives)} bundles for {instance_id}, nothing to clean up")
            return
        archives.sort(key=lambda archive: archive['last_modified'], reverse=True)
        to_delete = archives[max_bundles_to_keep:]
        for old in to_delete:
            canonical_prefix = f"ecs_{instance_id}/{old['execution_id']}/"
            delete_keys = []
            for page in paginator.paginate(Bucket=bucket, Prefix=canonical_prefix):
                delete_keys.extend({'Key': obj['Key']} for obj in page.get('Contents', []))
            delete_keys.append({'Key': old['key']})
            if delete_keys:
                for index in range(0, len(delete_keys), 1000):
                    s3_client.delete_objects(
                        Bucket=bucket,
                        Delete={'Objects': delete_keys[index:index + 1000], 'Quiet': True},
                    )
                print(f"Cleaned up old bundle: {old['key']} ({len(delete_keys)} objects deleted)")
        print(f"Bundle cleanup complete for {instance_id}: kept {max_bundles_to_keep}, deleted {len(to_delete)} old bundles")
    except Exception as e:
        print(f"Warning: Bundle cleanup failed (non-fatal): {str(e)}")

def lambda_handler(event, context):
    print(f"Received event: {json.dumps(event)}")
    for record in event.get('Records', []):
        bucket = record['s3']['bucket']['name']
        key = unquote_plus(record['s3']['object']['key'])
        if '/extracted/' in key:
            print(f"Skipping already extracted file: {key}")
            continue
        is_zip = key.lower().endswith('.zip')
        is_targz = key.lower().endswith('.tar.gz') or key.lower().endswith('.tgz')
        if not is_zip and not is_targz:
            print(f"Skipping unsupported file type: {key}")
            continue
        extract_prefix = resolve_extract_prefix(key)
        if not extract_prefix:
            print(f"SECURITY: Unsupported archive key layout: {key}")
            continue
        print(f"Processing archive: s3://{bucket}/{key} into {extract_prefix}")
        try:
            response = s3_client.get_object(Bucket=bucket, Key=key)
            content = response['Body'].read()
            if is_zip:
                extracted_files, prefix = extract_zip(bucket, key, content, extract_prefix)
            else:
                extracted_files, prefix = extract_targz(bucket, key, content, extract_prefix)
            print(f"Successfully extracted {len(extracted_files)} files from {key}")
            generate_manifest(bucket, prefix, extracted_files, key, len(content))
            trigger_findings_indexer(bucket, prefix, len(extracted_files))
            cleanup_old_bundles(bucket, key, max_bundles_to_keep=2)
        except (zipfile.BadZipFile, tarfile.TarError) as e:
            print(f"Error: {key} is not a valid archive: {str(e)}")
        except Exception as e:
            print(f"Error processing {key}: {str(e)}")
            raise e
    return {'statusCode': 200, 'body': json.dumps({'message': 'Archive extraction complete'})}
`;
  }

  private getFindingsIndexerCode(): string {
    return `
import json
import boto3
import os
import re
from datetime import datetime

s3_client = boto3.client('s3')
LOGS_BUCKET = os.environ['LOGS_BUCKET_NAME']

# ECS-specific scannable file patterns
SCANNABLE_FILE_PATTERNS = [
    r'ecs[-_]agent',
    r'ecs[-_]init',
    r'docker[/.]',
    r'containerd[/-]log',
    r'dmesg',
    r'messages',
    r'secure',
    r'syslog',
    r'journal',
    r'containers/',
    r'container-logs',
    r'var_log/.*\\.log',
    r'networking',
]
SCANNABLE_REGEXES = [re.compile(p, re.IGNORECASE) for p in SCANNABLE_FILE_PATTERNS]

SKIP_FILE_PATTERNS = [
    r'sysctl', r'ethtool', r'ifconfig', r'conntrack\\.txt',
    r'pkglist', r'ps\\.txt', r'ps-threads', r'top\\.txt',
    r'allprocstat', r'mounts\\.txt', r'modinfo', r'iptables',
    r'metrics\\.json', r'\\.json$', r'\\.yaml$', r'\\.yml$',
    r'\\.conf$', r'\\.toml$', r'\\.service$',
    r'docker-info', r'docker-ps', r'docker-images',
    r'instance-', r'metadata',
]
SKIP_REGEXES = [re.compile(p, re.IGNORECASE) for p in SKIP_FILE_PATTERNS]

# ECS-specific error patterns for findings indexer
ERROR_PATTERNS = {
    'critical': [
        (r'(?i)agent.*connected.*false', 'ECS Agent disconnected'),
        (r'(?i)AGENT_DISCONNECTED', 'ECS Agent disconnected from cluster'),
        (r'(?i)failed.*register.*container.*instance', 'Container instance registration failed'),
        (r'(?i)CannotPullContainerError', 'Cannot pull container image'),
        (r'(?i)CannotPullECRContainerError', 'Cannot pull ECR container image'),
        (r'(?i)ResourceInitializationError', 'Resource initialization failed'),
        (r'(?i)TaskFailedToStart', 'Task failed to start'),
        (r'(?i)CannotStartContainerError', 'Cannot start container'),
        (r'(?i)CannotCreateContainerError', 'Cannot create container'),
        (r'(?i)ContainerRuntimeError', 'Container runtime error'),
        (r'(?i)pull.*access.*denied', 'Image pull access denied'),
        (r'(?i)repository.*does.*not.*exist', 'Repository does not exist'),
        (r'(?i)unauthorized.*authentication.*required', 'Authentication required'),
        (r'(?i)toomanyrequests.*Too Many Requests', 'Docker Hub rate limit'),
        (r'(?i)unable to pull secrets or registry auth', 'Secrets/registry auth failed'),
        (r'(?i)docker.*daemon.*not.*running', 'Docker daemon not running'),
        (r'(?i)OCI runtime create failed', 'OCI runtime create failed'),
        (r'(?i)no.*space.*left.*device', 'No space left on device'),
        (r'(?i)invoked oom-killer', 'OOM killer invoked'),
        (r'(?i)Out of memory: Kill', 'OOM kill'),
        (r'(?i)Memory cgroup out of memory', 'cgroup OOM'),
        (r'(?i)kernel.*panic', 'kernel panic'),
        (r'(?i)segfault', 'segfault'),
        (r'(?i)ENI.*allocation.*failed', 'ENI allocation failed'),
        (r'(?i)InsufficientFreeAddressesInSubnet', 'IP exhaustion'),
        (r'(?i)deployment circuit breaker.*triggered', 'Circuit breaker triggered'),
        (r'(?i)AccessDeniedException', 'Access denied'),
        (r'(?i)exit code 137', 'Container killed (OOM)'),
        (r'(?i)exit code 139', 'Container segfault'),
        (r'(?i)SpotInterruptionError', 'Spot interruption'),
    ],
    'warning': [
        (r'(?i)health.*check.*failed', 'Health check failed'),
        (r'(?i)UNHEALTHY', 'Container unhealthy'),
        (r'(?i)task.*stopped', 'Task stopped'),
        (r'(?i)Essential container.*exited', 'Essential container exited'),
        (r'(?i)service.*was unable to place a task', 'Task placement failure'),
        (r'(?i)connection.*refused', 'Connection refused'),
        (r'(?i)connection.*timeout', 'Connection timeout'),
        (r'(?i)TLS.*handshake.*timeout', 'TLS timeout'),
        (r'(?i)DNS.*failed', 'DNS resolution failed'),
        (r'(?i)memory.*pressure', 'Memory pressure'),
        (r'(?i)cpu.*throttl', 'CPU throttling'),
        (r'(?i)log.*driver.*error', 'Log driver error'),
        (r'(?i)awslogs.*error', 'awslogs driver error'),
        (r'(?i)docker.*restart', 'Docker restarted'),
        (r'(?i)is not authorized to perform', 'IAM permission denied'),
        (r'(?i)OOMKilled', 'Container OOMKilled'),
        (r'(?i)conntrack.*table.*full', 'Conntrack table full'),
    ],
    'info': [
        (r'(?i)level=(?:warn|warning)', 'log-level warning'),
        (r'(?i)DEPRECATION:', 'deprecation notice'),
        (r'(?i)context deadline exceeded', 'context deadline'),
        (r'(?i)retrying', 'retrying operation'),
    ],
}

COMPILED_PATTERNS = {}
for _sev, _pats in ERROR_PATTERNS.items():
    COMPILED_PATTERNS[_sev] = []
    for _pat, _desc in _pats:
        try:
            COMPILED_PATTERNS[_sev].append((re.compile(_pat), _desc))
        except re.error:
            pass

def is_scannable(filename):
    for skip_re in SKIP_REGEXES:
        if skip_re.search(filename):
            return False
    for scan_re in SCANNABLE_REGEXES:
        if scan_re.search(filename):
            return True
    if filename.endswith('.log') or filename.endswith('.txt'):
        log_dirs = ['ecs-agent', 'docker', 'var_log', 'kernel', 'system/messages']
        return any(d in filename for d in log_dirs)
    return False

def lambda_handler(event, context):
    print(f"Received event: {json.dumps(event)}")
    bucket = event.get('bucket', LOGS_BUCKET)
    prefix = event.get('prefix', '')
    if not prefix:
        return {'statusCode': 400, 'body': 'No prefix provided'}
    try:
        files_to_scan = []
        files_skipped = 0
        paginator = s3_client.get_paginator('list_objects_v2')
        for page in paginator.paginate(Bucket=bucket, Prefix=prefix):
            for obj in page.get('Contents', []):
                key = obj['Key']
                if any(key.endswith(ext) for ext in ['.tar.gz', '.zip', '.gz', '.bin', '.so']):
                    continue
                if obj['Size'] > 5242880:
                    continue
                filename = key.split('/extracted/')[-1] if '/extracted/' in key else key
                if not is_scannable(filename):
                    files_skipped += 1
                    continue
                files_to_scan.append({'key': key, 'size': obj['Size']})
        print(f"Scanning {len(files_to_scan)} log files ({files_skipped} non-log files skipped)")
        all_findings = []
        for file_info in files_to_scan[:200]:
            findings = scan_file(bucket, file_info['key'])
            all_findings.extend(findings)
        deduplicated = deduplicate_findings(all_findings)

        # False positive suppression
        FALSE_POSITIVE_SUPPRESSIONS = [
            ('DNS.*failed', r'health[-.]?check|readiness|liveness', 'Health check DNS'),
            ('OOMKilled', r'stress[-.]?test|load[-.]?test|chaos', 'Stress test'),
            ('connection refused', r'127\\.0\\.0\\.1.*healthz', 'Local healthz'),
            ('TLS handshake', r'health[-.]?check', 'Probe TLS'),
        ]
        suppressed_count = 0
        filtered = []
        for f in deduplicated:
            suppressed = False
            pat = f.get('pattern', '')
            ctx = f.get('sample', '')
            for err_pat, fp_regex, reason in FALSE_POSITIVE_SUPPRESSIONS:
                if re.search(err_pat, pat, re.IGNORECASE):
                    if re.search(fp_regex, ctx, re.IGNORECASE):
                        suppressed = True
                        suppressed_count += 1
                        break
            if not suppressed:
                filtered.append(f)
        deduplicated = filtered

        for idx, finding in enumerate(deduplicated):
            finding['finding_id'] = f"F-{idx + 1:03d}"
            finding['evidence'] = {'source_file': finding.get('file', ''), 'full_key': finding.get('fullKey', ''), 'excerpt': finding.get('sample', '')[:500], 'line_range': {'start': finding.get('line', 0), 'end': finding.get('line', 0)}}

        # Multi-signal confirmation for critical findings
        pattern_files = {}
        for f in deduplicated:
            p = f.get('pattern', '')
            if p not in pattern_files:
                pattern_files[p] = set()
            pattern_files[p].add(f.get('file', ''))
        for f in deduplicated:
            if f.get('severity') == 'critical':
                sources = list(pattern_files.get(f.get('pattern', ''), set()))
                f['confirmation'] = {'signals': len(sources), 'confirmed': len(sources) >= 2, 'sources': sources[:5]}
                if len(sources) < 2:
                    f['severity_note'] = 'Single-source critical finding. Verify with additional log sources.'

        summary = {
            'critical': len([f for f in deduplicated if f.get('severity') == 'critical']),
            'high': len([f for f in deduplicated if f.get('severity') in ('warning', 'high')]),
            'medium': len([f for f in deduplicated if f.get('severity') == 'medium']),
            'low': len([f for f in deduplicated if f.get('severity') == 'low']),
            'info': len([f for f in deduplicated if f.get('severity') == 'info']),
        }
        total_files_in_bundle = len(files_to_scan) + files_skipped
        coverage = {'files_scanned': len(files_to_scan), 'total_files': total_files_in_bundle, 'coverage_pct': round(len(files_to_scan) / max(total_files_in_bundle, 1) * 100, 1), 'files_skipped': files_skipped, 'suppressed_false_positives': suppressed_count}
        index_data = {'index_version': 'v2', 'indexedAt': datetime.utcnow().isoformat(), 'prefix': prefix, 'coverage': coverage, 'filesScanned': len(files_to_scan), 'filesSkipped': files_skipped, 'findings': deduplicated[:500], 'summary': summary}
        index_key = f"{prefix}findings_index.json"
        s3_client.put_object(Bucket=bucket, Key=index_key, Body=json.dumps(index_data, default=str), ContentType='application/json')
        print(f"Wrote findings index to {index_key}")
        print(f"Summary: {summary}")
        return {'statusCode': 200, 'body': json.dumps({'message': 'Findings indexed', 'indexKey': index_key, 'summary': summary})}
    except Exception as e:
        print(f"Error indexing findings: {str(e)}")
        return {'statusCode': 500, 'body': str(e)}

def scan_file(bucket, key):
    findings = []
    try:
        response = s3_client.get_object(Bucket=bucket, Key=key, Range='bytes=0-1048575')
        content = response['Body'].read()
        try:
            content_str = content.decode('utf-8')
        except:
            content_str = content.decode('latin-1', errors='ignore')
        filename = key.split('/extracted/')[-1] if '/extracted/' in key else key
        lines = content_str.split('\\n')[:5000]
        for severity, compiled_list in COMPILED_PATTERNS.items():
            for regex, description in compiled_list:
                match_count = 0
                for i, line in enumerate(lines):
                    if regex.search(line):
                        findings.append({'file': filename, 'fullKey': key, 'severity': severity, 'pattern': description, 'line': i + 1, 'sample': line.strip()[:300]})
                        match_count += 1
                        if match_count > 50 or len(findings) > 200:
                            break
                if len(findings) > 200:
                    return findings
    except Exception as e:
        print(f"Error scanning {key}: {str(e)}")
    return findings

def deduplicate_findings(findings):
    seen = {}
    for finding in findings:
        dedup_key = f"{finding.get('file')}:{finding.get('pattern')}"
        if dedup_key not in seen:
            seen[dedup_key] = {**finding, 'count': 1, 'lines': [finding.get('line')], 'first_seen': finding.get('sample', '')[:50], 'last_seen': finding.get('sample', '')[:50]}
        else:
            seen[dedup_key]['count'] += 1
            if len(seen[dedup_key]['lines']) < 10:
                seen[dedup_key]['lines'].append(finding.get('line'))
            seen[dedup_key]['last_seen'] = finding.get('sample', '')[:50]
    severity_map = {'warning': 'high'}
    for entry in seen.values():
        old_sev = entry.get('severity', 'info')
        if old_sev in severity_map:
            entry['severity'] = severity_map[old_sev]
    severity_order = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3, 'info': 4}
    return sorted(seen.values(), key=lambda x: (severity_order.get(x.get('severity'), 4), -x.get('count', 0)))
`;
  }
}
